salesforcecli/plugin-org

- src/commands/force/org/display.ts
refresh auth before reading the files to prevent display of stale accessTokens
@W-8886636@
> fix: refresh before reading files

- .circleci/config.yml
- package.json
- src/shared/orgHighlighter.ts
- src/shared/orgListUtil.ts
- test/nut/commands/force/org/org.nut.ts
- test/shared/orgHighlighter.test.ts
- yarn.lock
Add new nut tests for plugin-org
@W-8856585@
> chore: add nut tests for plugin-org

- messages/list.json
- messages/open.json
- src/commands/force/org/list.ts
Cleans up help and adds examples back to force:org:list
@W-8995248@
> fix: clean up help and add examples back to force:org:list

- messages/display.json
- package.json
- src/commands/force/org/display.ts
- src/shared/orgListUtil.ts
- test/nut/commands/force/org/org.nut.ts
- test/shared/orgListUtil.test.ts
- yarn.lock
previous version was filtering out auth files based on the presence of the userId property...these were typically created by `user:create` (secondary user on an org)
But they can also be created by `user:password:generate` on a primary user.
This fix uses the org's json file to help identify other reasons the file can represent a primary user
Fix to error messaging when a hub fails to provide scratch org information https://github.com/forcedotcom/cli/issues/944
also bumps testkit to latest so retries happen for org:create
@W-9042306@ https://github.com/forcedotcom/cli/issues/940 https://github.com/forcedotcom/cli/issues/944
> fix: list command shows orgs that have userId

- src/shared/utils.ts
- test/shared/utils.test.ts
when there are multiple aliases for the username, use the last (most recent) alias
@W-9351642@
https://github.com/forcedotcom/cli/issues/1031
> fix: use most recent alias

- src/shared/orgListUtil.ts
- test/nut/commands/force/org/org.nut.ts
adds the scratch org namespace value to json output of org:list (for parity...org display already had that field) 
@W-9788406@
https://github.com/forcedotcom/cli/issues/1146
> feat: namespace on orgList

- messages/display.json
because output contains sfdx auth url which contains refresh token which contains sensitive information
See above. Here's a screenshot of resulting --help output:
@W-10165230@
> fix: add warning about using force:org:display --verbose

- command-snapshot.json
- messages/delete.json
- package.json
- src/commands/force/org/delete.ts
- src/shared/orgListUtil.ts
- test/commands/force/org/delete.test.ts
- test/nut/commands/force/org/delete.org.nut.ts
- yarn.lock
migrates `org:delete` from toolbelt
carries over messages and error messages
uses sfdx-core for new `delete` method on `Org`
requires https://github.com/forcedotcom/sfdx-core/pull/491
> fix: org:delete scratch org + sandboxes

- src/commands/force/org/beta/create.ts
- test/commands/force/org/scratchOrgCreate.test.ts
Tries to create local config first then falls back to global config in order to set the default username
1) if you want you can use `./bin/run` or link this plugin in sfdx by doing `sfdx plugins:link .` in the root of this folder
2) Using an org like `dreamhouse-lwc` create a new scratch org with the legacy command: `sfdx force:org:create -f config/project-scratch-def.json --setalias dreamhouse-lwc-legacy --durationdays 1 --setdefaultusername` 
3) Check out the default username with `sfdx config:list`
4) Create a new scratch org with beta command: `sfdx force:org:beta:create -f config/project-scratch-def.json --setalias dreamhouse-lwc --durationdays 1 --setdefaultusername`
5) Finally check the default username has changed with: `sfdx config:list`
@W-10675890@
> fix: try to create local config first

- messages/list.json
clarify that org:list --clean only deletes expired scratch orgs
https://github.com/forcedotcom/cli/issues/1449
@W-10886099@
> fix: docs for clean flag

- messages/clone.json
- messages/display.json
- messages/list.json
- messages/open.json
- messages/status.json
- src/commands/force/org/clone.ts
Adds back a long description for "wait" that somehow got lost along the way. 
I also updated the examples so that they render correctly in the generated CLI Ref.
@W-11152197@
> Add back missing long description for "wait"

- package.json
- src/commands/force/org/beta/create.ts
- test/commands/force/org/scratchOrgCreate.test.ts
- yarn.lock
> requires https://github.com/forcedotcom/sfdx-core/pull/620
`org:beta:create` will use the latest sfdx-core scratchOrgCreate code so that it
1. sets the alias properly [@W-11404235@](https://gus.lightning.force.com/a07EE0000110WJgYAM)
2. sets `tracksSource` property on the org to account for non-prod environments that answer `isSandbox()` incorrectly [@W-11357043@](https://gus.lightning.force.com/a07EE000010DFqtYAG)
> fix: use newer core scratchOrgCreate

- src/commands/force/org/beta/create.ts
- test/commands/force/org/sandboxCreate.test.ts
- test/commands/force/org/scratchOrgCreate.test.ts
Sets `durationdays` flag value to 7 days by default for `force:org:beta:create`, this matches the current org create command from toolbelt.
the flag value was being passed as undefined to the scratch org payload, then the API would set the duration to 1 day.
if `--durationdays` isn't passed org:beta:create will default to 7 days.
@W-0@
> fix: set scratch org duration to 7days by default

- package.json
- src/shared/orgListUtil.ts
- yarn.lock
Fixes the path when reading user json file when the org is referenced in a `00D` file.
@W-11507149@
https://github.com/forcedotcom/cli/issues/1641
> fix: org list now lists all scratch orgs properly

- src/commands/force/org/create.ts
Reinstates lifecycleEventNames prop so that force:org:create will run postorgcreate hooks.
What issues does this PR fix or reference?
[@forcedotcom/cli/issues/1722@](https://github.com/forcedotcom/cli/issues/1722)
> 1722: Re-instate lifecycleEventNames so postorgcreate is emitted.

- test/nut/commands/force/org/org.nut.ts
NUT matches what the command's flag.parse is using for urlencoding the path
This seems to work in this repo's NUTs (encodes), and work locally (encodes) but fails on just-nuts (no encoding).
https://github.com/salesforcecli/sfdx-cli/actions/runs/3491014374/jobs/5843317166
** I have no idea why! **
The goal of this PR is that whatever differences may exist at runtime, they match.
[@W-12084293@](https://gus.lightning.force.com/a07EE00001DUJmwYAH)
> test: remove deprecated querystring

- src/commands/force/org/create.ts
It ensures that if an error is thrown in an underlying library when attempting to create a Sandbox it will be thrown by this plugin instead of swallowed.
Before this change:
1. Clone this repo
1. Ensure you're on the `main` branch
1. Run `bin/dev force:org:create -t sandbox sandboxName=testSandbox licenseType=Developer -u <devhub>` against an org that can't create sandboxes such as a basic developer edition org.
1. The command exits with a `0` status code and no error.
After this change:
1. Checkout this branch, `re/return-errors`
1. Run `bin/dev force:org:create -t sandbox sandboxName=testSandbox licenseType=Developer -u <devhub>` against the same org
1. You should see an error that says the following:
```bash
ERROR running force:org:create:  The requested resource does not exist
``` …
> fix: always throw errors caught from creating sandboxes

- command-snapshot.json
- messages/delete.md
- src/commands/force/org/delete.ts
We deleted an unused flag.  This puts a hidden, dummy string flag in its place to avoid breaking changes.  It'll include warnings for anyone who uses it (the entire command is deprecated anyway).
https://github.com/forcedotcom/cli/issues/1925
[@W-12563970@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001LRZwyYAH/view)
> fix: restore hub flag on org:delete

- src/commands/org/create/sandbox.ts
- src/commands/org/create/scratch.ts
- src/commands/org/delete/sandbox.ts
- src/commands/org/delete/scratch.ts
- src/commands/org/resume/sandbox.ts
Removes beta tag from org commands.
Users running the deprecated commands get a warn to use the new commands, but these are still marked as beta.
See: https://twitter.com/JHMSchwarzer/status/1626930091811868672
@W-0@
> fix: remove beta tag from org commands

- src/commands/org/open.ts
I noticed that `force org open` was not showing a command deprecation warning. This PR fixes a typo and it now shows
> fix: deprecation warning

- package.json
We have been seeing `Workerpool Worker terminated Unexpectedly` [in GHA lately](https://github.com/salesforcecli/sfdx-cli/actions/runs/4673995439/jobs/8278143327#step:6:343). Some places online suggest this is a memory issue, this PR lowers the parallel jobs
[skip-validate-pr] [no-ci]
> lower parallel nut jobs

- src/commands/force/org/delete.ts
- src/commands/org/delete/sandbox.ts
- src/commands/org/delete/scratch.ts
- src/shared/flags.ts
- test/nut/scratchDelete.nut.ts
- test/unit/force/org/delete.test.ts
- test/unit/org/list.test.ts
can delete a default org when it's an alias
> fix: can delete default being an alias

- messages/create_scratch.md
- messages/delete_sandbox.md
- messages/delete_scratch.md
Some examples still used "sfdx" style for flags (i.e. --edition=developer); changed it to sf style (--edition developer). 
@W-13501919@
> fix: small fixes to --help examples

- src/commands/force/org/create.ts
Removes a log line that causes this error:
```
Error (1): Converting circular structure to JSON
--> starting at object with constructor 'Timeout'
|     property '_idlePrev' -> object with constructor 'TimersList'
--- property '_idleNext' closes the circle
```
@W-13123532@
> fix: remove logging that caused circular ref

- messages/create.md
- messages/delete.md
- messages/display.md
- messages/list.md
- messages/messages.md
Cleans up help and error messages, trying to consistently name the new commands without colons, and more stuff. 
@W-13555106@
> fix: make help/errors more consistent when naming new commands

- src/shared/orgListUtil.ts
Prevents https://github.com/forcedotcom/cli/issues/2222 from happening again.
This was unintentionally fixed in https://github.com/forcedotcom/sfdx-core/pull/842
[@W-13602928@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13602928)
QA
I reverted back to an older version of the CLI (1.194.1) and then I modified `plugin-org` directly with the same `mkdir` code
Confirm existing directory does not cause issues
> Ensure sfdx dir exists

- package.json
- test/.eslintrc.js
- test/nut/legacy/sandbox.sandboxNut.ts
- test/nut/legacy/status.sandboxNut.ts
- test/nut/sandbox.sandboxNut.ts
- test/shared/orgListUtil.test.ts
- test/shared/sandboxProgress.test.ts
- test/shared/sandboxReporter.test.ts
- test/shared/utils.test.ts
- test/unit/force/org/sandboxCreate.test.ts
- test/unit/org/createSandbox.test.ts
- test/unit/org/display.test.ts
- test/unit/org/list.test.ts
- yarn.lock
don't use async without await
eslint to prevent future misuse
maybe help with https://github.com/forcedotcom/sfdx-core/actions/runs/5467770306/jobs/9954535647?pr=876#step:13:98
> test: accurate async/await and tighter eslint

- src/commands/org/list.ts
- src/shared/orgListUtil.ts
- test/shared/orgListUtil.test.ts
we've been ignoring `--skip-connection-status` since this command was sf-ified.  Flags weren't typed before.
[@W-13957953@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001YYxGYYA1/view)
> fix: skip-connection-status flag works

- src/shared/orgListUtil.ts
- test/shared/orgListUtil.test.ts
handlers for html reponses for org status, including special handling for the maintenance scenario
https://github.com/forcedotcom/cli/issues/2487
@W-14178119@
> fix: handle html maintenance message

- messages/open.md
- src/commands/org/open.ts
- test/nut/open.nut.ts
- yarn.lock
org:open --source-file can open a flow in flow builder
https://github.com/forcedotcom/cli/discussions/2519
@W-14287109@
> feat: open a flow

- src/commands/org/open.ts
Awesome customers like @GusjkoA help with QA and found a way the previous version of this wouldn't work.
https://github.com/forcedotcom/cli/discussions/2519
@W-14287109@
> fix: don't use tooling api to get flow id

- messages/open.md
Fixes examples that use --source-path instead of the correct --source-file
> fix: examples should use --source-file, not --source-path

- src/shared/orgListUtil.ts
- test/shared/orgListUtil.test.ts
Improves error handler when trying to get status of an org. 
before:
`org list` would check for `<html>` in err message
after:
`org list` will check for `html` **or** `<!DOCTYPE HTML>` to ensure it got an HTML response from the server.
Repro:
modify the instance url (make it point to an invalid url) of a non-hub org in its auth file, then run `sf org list`
https://github.com/forcedotcom/cli/issues/2533
@W-14348441@
> fix(org status): improve err handling

- src/commands/org/open.ts
Check for both `SF_CONTAINER_MODE` and `SFDX_CONTAINER_MODE`
Check for both `SF_DOMAIN_RETRY` and `SFDX_DOMAIN_RETRY`
@W-14437987@
#2554
> fix: check for both sf and sfdx env vars

- LICENSE.txt
- src/commands/org/create/scratch.ts
Make `org create scratch --edition` handle `parter-*` values properly.
We are setting the `Edition` field for `ScratchOrgInfo` to `parter-<EDITION>` but the API expects these as `partner <EDITION>` (separated by space, no hyphen).
Keeping the `parter-<EDITION>` format allow us to still autocomplete these (can't insert values with spaces on zsh).
Repro:
1) try to create a scratch org with any of the allowed partner edition values:
```
➜  ~ sf org create scratch --edition partner-developer
Creating Scratch Org... Error
Error (1): Edition: bad value for restricted picklist field: partner-developer
```
2) link this branch of plugin-org into sf, then:
```
➜  ~ sf org create scratch --edition partner-developer
›   Warning: @salesforce/plugin-org is a linked ESM module and cannot be …
```
> fix: properly parse edition flag

- LICENSE.txt
- src/commands/force/org/clone.ts
- src/commands/force/org/create.ts
- src/commands/force/org/delete.ts
- src/commands/force/org/status.ts
What does this PR do?
marks deprecated commands as hidden
[keep them out of docs, autocomplete, etc]
What issues does this PR fix or reference?
@W-14739853@
> feat: hide deprecated commands

- src/commands/org/open.ts
Follow up from https://github.com/salesforcecli/plugin-org/pull/913
`sf org open --path <path>` isn't working on current nightly (sf v2.25.5).
`--path` is URI-encoded by default (for the old behavior of opening the url with the AT + path | source-file as param), but the form redirect requires is to be decoded:
tested on macos (firefox/chrome) and windows (firefox/edge)
> fix: decode `path` flag before writing it to form

- messages/create.sandbox.md
- messages/refresh.sandbox.md
- src/commands/org/refresh/sandbox.ts
Edit messages for new "org refresh sandbox" command.  Also adds info and exmaple about cloning a sandbox to the "org create sandbox" messages -- I noticed it was missing. 
@W-15134034@
> doc: edit messages for new "org refresh sandbox" command

- package.json
- test/nut/async-create-resume.nut.ts
- test/nut/listAndDisplay.nut.ts
- test/nut/metadata.nut.ts
- test/nut/open.nut.ts
- test/nut/sandboxRefresh.nut.ts
- test/nut/scratchCreate.nut.ts
- test/nut/scratchDelete.nut.ts
- test/nut/tracking.nut.ts
- test/shared/sandboxMockUtils.ts
Changes the sandbox refresh and create NUTs to ensure a unique TestSession dir.
> fix: fix NUTs for sbx refresh

- command-snapshot.json
- messages/refresh.sandbox.md
- src/commands/org/refresh/sandbox.ts
Changes the `auto-activate` flag to `no-auto-activate` since that is the only valid way to disable the default behavior anyway. 
@W-15042183@
> test: change to no-auto-activate flag

- src/commands/org/open.ts
Make `org open` command to convert Linux file path to Windows one in WSL.
`org open` command was changed to open temp html file from to open url directly.
In WSL, the command silently fails because Windows browser tries to open linux file path.
https://github.com/forcedotcom/cli/issues/2677
[@W-15278875@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-15278875)
> fix: convert linux file path to Windows one in WSL

- src/commands/org/create/sandbox.ts
- test/nut/sandboxCreate.nut.ts
- test/shared/sandboxMockUtils.ts
Allows the sandbox name and license type to be overridden with flags while also using a definition file per the discussion here: https://github.com/forcedotcom/cli/discussions/2511#discussioncomment-8497017
@W-15141701@
> feat: allow sandbox name and license-type overrides

- messages/refresh.sandbox.md
Fixes typo in description that says "production org" instead of "source org". 
@W-15458307@
> fix: typo in description

- test/shared/sandboxMockUtils.ts
Adds a 100ms delay before returning stubbed query responses for a more realistic test and to prevent issues with sandbox cache (ConfigFile) merging/writing.
@W-15534516@
> fix: delay stubbed query responses for more realistic tests

- messages/delete_sandbox.md
- messages/delete_scratch.md
Sets the summary for --target-org for the org delete scratch|sandbox commands to be the same as other --target-org summaries.  These two commands dont' use the standard definition of the flag. 
@W-15895281@
> fix: improve --target-org summaries of "org delete scratch|sandbox"

- src/commands/org/display.ts
- src/shared/orgTypes.ts
- test/unit/org/display.test.ts
Fix a bug where `org display` would return wrong info about a scratch org when its 15-char ID matches other `ScratchOrgInfo` records in the hub.
the query runs here:
https://github.com/salesforcecli/plugin-org/blob/49c4e33cf3a612b4f2344f0d0fe11aa0de3e223a/src/shared/orgListUtil.ts#L244C1-L251C43
and gets translated to this SOQL query:
```sql
SELECT CreatedDate, Edition, Status, ExpirationDate, Namespace, OrgName, CreatedBy.Username, SignupUsername FROM ScratchOrgInfo WHERE ScratchOrg IN ('org-id')
```
The `IN` operator is case-sensitive if the fields it operates on are, `ScratchOrgInfo.ScratchOrg` **is not**:
```
sf sobject describe --sobject ScratchOrgInfo --target-org na40 --json | jq '.result.fields | .[] | select (.name == "ScratchOrg") | .caseSensitive'
> false
``` …
> fix: ensure org display picks the correct record

- package.json
- src/commands/force/org/create.ts
- src/commands/org/open.ts
- src/commands/org/resume/sandbox.ts
- src/shared/orgListUtil.ts
- src/shared/sandboxProgress.ts
- src/shared/sandboxReporter.ts
- yarn.lock
@W-16115298@
https://github.com/forcedotcom/eslint-config-salesforce-typescript/actions/runs/9717897647/job/27683284767?pr=246
> fix: nullish-linter

- src/commands/org/create/sandbox.ts
- src/commands/org/list/metadata-types.ts
- src/commands/org/list/metadata.ts
- src/commands/org/refresh/sandbox.ts
moves regular output into a table for 
`list metadata` 
`list metadata-types`
@W-6015646@
> feat: list metadata/-types stdout is table

- src/commands/org/list.ts
Updates `--no-prompt` flag in `org list` to use oclif's relationship feature instead of `dependsOn` a boolean flag.
Found by the new eslint rule:
https://github.com/salesforcecli/eslint-plugin-sf-plugin/actions/runs/10097996137/job/27924153782?pr=447
no behavior change because `--no-prompt` was dependingOn `--clean` which didn't have a default value so it was working as expected:
```
➜  sf sf org list --no-prompt
Error (2): The following error occurred:
All of the following must be provided when using --no-prompt: --clean
See more help with --help
```
@W-16320656@
> fix(flags): no `dependsOn` boolean flags

- messages/rest.md
- src/commands/org/api/rest.ts
quick edit of messages for hidden command "org api rest". note that I removed the command description because we don't restate that --target-org is required, and there was nothing else in the description. That's fine, command descriptions are optional.  If there's something else to say please add it back!
@W-16451172@
> edit messages of "org api rest"

- messages/clone.md
- messages/create.sandbox.md
- package.json
- src/commands/org/create/sandbox.ts
- src/commands/org/refresh/sandbox.ts
- src/shared/sandboxRequest.ts
- yarn.lock
create name feature in definition-file for apex and group option fields 
https://github.com/forcedotcom/cli/issues/3008#issuecomment-2342416748
@W-16757770@
> feat: name fields for definitionfile

- messages/open.md
- src/commands/org/open.ts
Will open the Bot Builder if you pass a `.bot-meta.xml` file to the `--source-file` flag.
Example:
`sf org open --source-file force-app/main/default/bots/Coral_Cloud_Agent/Coral_Cloud_Agent.bot-meta.xml`
https://github.com/user-attachments/assets/aa5af938-4190-4f5d-81a1-a9de998275a4
[@W-16954218@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-16954218)
> Open bot via the `--source-file` flag

- messages/open.agent.md
Edits messages for "org open agent"
@W-17205614@
> edit messages

- src/commands/org/display.ts
- src/shared/orgListUtil.ts
- src/shared/orgTypes.ts
- test/unit/org/display.test.ts
When running `sf org display` with a target-org that is not the scratch org admin user, the code would not match the ScratchOrgInfo SignupUser and would throw an error that the dev hub does not have a scratch org record with the provided org ID.  The code now tries to match the ScratchOrgInfo.LoginUrl with the target-org's instanceUrl as an additional way to match.  With this change, a user created within the scratch org can also have org details displayed when that user is the target-org username.
@W-17545444@
> fix: match on loginUrl/instanceUrl of ScratchOrgInfo if username does not match

- src/commands/org/display.ts
Updates `org display` table to avoid truncating cells.
This table is pretty small (2 columns) so it doesn't change much other than helping see long values (`Sfdx Auth Url` and `Access Token` if using JWT-based ones).
Users can override the overflow behavior globally via `SF_TABLE_OVERFLOW`, this is more of a "sane default" for this specific table (bigger tables definitely need to wrap cells in some cases to be readable).
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_env_variables.htm#sfdx_dev_cli_env_variables
> fix(org display): dont truncate table cells 

- command-snapshot.json
- messages/refresh.sandbox.md
- src/commands/org/refresh/sandbox.ts
fix issue: running` sf org refresh sandbox --name sbx --target-org prodOrgAlias` using `sourceSandboxName` to clone from different existing sandbox production.
it works with ` sourceId` and not `sourceSandboxName`. 
Add flag feature: `'source-id'` and `'source-sandbox-name'`.
**Note**: it should only be specify to use either one, but not both. Use flag or in the definition file to specify which existing sandbox to clone.
**Step to Reproduce**:
`sbx1` and `sbx2` created off production
`sbx3` which is a clone of `sbx1`
run `sf org refresh sandbox --name sbx3 --target-org prodOrgAlias --definition-file dev.json`
Inside `dev.json` file:
```
{
"sourceSandboxName": "sbx2"
}
```
@W-18237102@
see more details: https://github.com/forcedotcom/cli/issues/3262
> fix: W-18237102 - refresh sandbox with sourceSandboxName

- command-snapshot.json
- messages/open.agent.md
- src/commands/org/open/agent.ts
changes `org open agent --name` -> `--api-name`
⚠️ : ideally will be merged 2 weeks before GA
@W-18459941@
> fix: change --name to --api-name for org open agent W-18459941
