salesforcecli/plugin-org

package.json

tries to re-run the package process 
@W-8668302@

chore: trigger build from version bump?

---

package.json

chore: bump version [skip-ci]

---

src/commands/force/org/list.ts
src/shared/orgListUtil.ts

unencrypt access tokens on org:list
https://github.com/forcedotcom/cli/issues/822
@W-8801250@

fix: unencrypt access tokens on org:list

---

src/commands/force/org/display.ts
test/commands/force/org/display.test.ts

@W-8866140@
https://github.com/forcedotcom/cli/issues/838

Org display get defaultusername

---

command-snapshot.json
src/commands/force/org/display.ts

removes supportsdevhub (mistakenly added)
@W-8951647@

fix: no devhub on display

---

package.json

runs the release process again from required manual version bump
@W-9042306@

chore: manual version bump (from prerel testing)

---

package.json
src/commands/force/org/display.ts
src/shared/utils.ts
yarn.lock

Migrates utility outside this repo into kit
@W-8752767@

chore: migrate util to kit

---

.circleci/config.yml

Reverts salesforcecli/plugin-org#67

Revert "chore: sync .circleci/config.yml"

---

messages/list.json

Adds a missing message when no scratch orgs are found
@W-9130097@

fix: add missing message

---

package.json
yarn.lock

pins `open` to 8.0.2 until https://github.com/sindresorhus/open/pull/238 is merged
@W-9177239@

chore: pin open to 8.0.2 until a bug is fixed

---

package.json
src/commands/force/org/open.ts
test/commands/force/org/open.test.ts
yarn.lock

It uses checkLightningDomain of sfdx-core in force:org:open command.
@W-9369342@

chore: using sfdx-core utill function

---

package.json

refactor: force release with patch bump

---

messages/list.json
src/commands/force/org/list.ts
src/shared/orgListUtil.ts
test/shared/orgListUtil.test.ts

Removes deprecation message
@W-9740004@

chore: remove deprecation message

---

messages/open.json

updates "yourinstance.salesforce.com" to "mydomainname.my.salesforce.com"
@W-9561593@

fix: update domain URL to be more secure

---

command-snapshot.json
messages/status.json
package.json
src/commands/force/org/status.ts
test/commands/force/org/display.test.ts
test/commands/force/org/list.test.ts
test/commands/force/org/open.test.ts
test/commands/force/org/status.test.ts
test/shared/orgListUtil.test.ts
test/shared/utils.test.ts
yarn.lock

Adds a `status` command for sandboxes
- Link [`sfdx-core`](https://github.com/forcedotcom/sfdx-core/pull/535) from this [PR](https://github.com/forcedotcom/sfdx-core/pull/535)
@W-10657353@

feat: new command org:status

---

messages/clone.json

To show which is the new sandbox, and which is the one you're cloning from. Also added more info to description.
Improves the example and description of cloning a sandbox
@W-11357618@

js: Improve sandbox cloning example and description

---

package.json

chore(release): 2.0.2 [ci skip]

---

package.json
yarn.lock

fix: bump version of @salesforce/core

---

package.json
yarn.lock

bumps core to include sandbox clone fix: https://github.com/forcedotcom/sfdx-core/pull/623
@W-0@

fix: bump salesforce/core

---

package.json
yarn.lock

fix: bump sfdx-core

---

package.json

bump to 2.1.7

---

test/nut/commands/force/org/beta/create.nut.ts

nut for the repro of https://github.com/forcedotcom/cli/issues/1669
@W-11598550@

test: intentionally failing nut

---

package.json
yarn.lock

bump sfdx-core for fix
@W-11598550@

feat: fix for mixed-case usernames

---

test/nut/commands/force/org/org.nut.ts

makes it easier to debug just-nuts by haivng chai not truncating the expected strings

test: don't truncate expected value

---

package.json
src/commands/force/org/clone.ts
src/commands/force/org/create.ts
src/commands/org/create/sandbox.ts
src/shared/orgHooks.ts
src/shared/sandboxProgress.ts
yarn.lock

Uses sf-plugins-core v2 and oclif/core v2
@W-10791948@

feat: use latest oclif/core

---

package.json

applies sf styles to topic descriptions in pacakge.json
@W-12490016@

fix: apply sf styles to topic desc

---

test/nut/listAndDisplay.nut.ts

Tries to fix a couple of list org NUTs failures
@W-12467406@

fix: windows list NUTs

---

messages/list.metadata.md
messages/metadata-types.md
messages/open.md
src/commands/org/list/metadata-types.ts
src/commands/org/list/metadata.ts

Edits sfized messages for "org list metadata" and "org list metadata-types", and new --source-file flag for "org open".
@W-12623662@

fix: edit messages for sf-ized list metadata commands

---

package.json
src/shared/stagedProgress.ts
yarn.lock

mitigate Cannot read properties of undefined (reading 'index')
@W-12731165@

fix: mitigate Cannot read properties of undefined (reading 'index')

---

messages/create.md
src/commands/force/org/create.ts
test/unit/force/org/scratchOrgCreate.test.ts

adds deprecation warnings for force:org:create

feat: gentle deprecation warning for force:org:create

---

src/commands/org/create/scratch.ts
src/commands/org/display.ts

group the "flags that override definition files"
@W-13303650@

docs: flag grouping for org create help

---

package.json
yarn.lock

bump deps, including testkit for session.clean bug
https://github.com/forcedotcom/sfdx-core/actions/runs/5477437565/jobs/9976954011#step:13:202

fix(deps): bump teskit, core, sdr, sf-plugins-core

---

README.md
package.json
src/commands/org/open.ts
test/nut/legacy/status.sandboxNut.ts
test/nut/metadata.nut.ts

removes `sfdx-cli` references for `sf`
@W-12607169@

chore: remove sfdx references

---

src/commands/org/create/sandbox.ts

Changes how duration flags are defined so the command reference generator correction picks up default values
@W-14002266@

fix: change default value definition

---

messages/org.disable.tracking.md
messages/org.enable.tracking.md
package.json

Edits messages for new "org enable|disable tracking" commands. 
@W-14513033@

Edit messages for new source-tracking commands

---

src/commands/org/list.ts
yarn.lock

Adds `namespace` column to `sf org list --verbose`.
@W-12009216@

feat: add namespace column (#596)

---

package.json
test/nut/scratchCreate.nut.ts
yarn.lock

test: expect nonZero exit code

---

command-snapshot.json

https://github.com/salesforcecli/cli/actions/runs/8089988440

fix: update snaphshot

---

README.md
command-snapshot.json
package.json
src/commands/org/disable/tracking.ts
src/commands/org/display.ts
src/commands/org/enable/tracking.ts
src/commands/org/list/metadata-types.ts
src/commands/org/list/metadata.ts
src/commands/org/resume/scratch.ts
src/shared/flags.ts
test/nut/legacy/sandbox.sandboxNut.ts
test/unit/force/org/sandboxCreate.test.ts
yarn.lock

Add `--flags-dir` to all commands by bumping @salesforce/sf-plugins-core to v8

feat: bump sf-plugins-core

---

.github/workflows/test.yml
package.json
test/nut/async-create-resume.nut.ts
test/nut/listAndDisplay.nut.ts
test/nut/metadata.nut.ts
test/nut/open.nut.ts
test/nut/sandbox.sandboxNut.ts
test/nut/sandboxCreate.nut.ts
test/nut/sandboxRefresh.nut.ts
test/nut/sandboxResume.nut.ts
test/nut/scratchCreate.nut.ts
test/nut/scratchDelete.nut.ts
test/nut/tracking.nut.ts

decrease parallelism to 2 (this actually reduces average time because there aren't retries).
I never figured out what was causing this or how to replicate it.  It *still* could be 
1. a legit bug with ConfigFile where cross-saved happen
2. something weird with Singletons (StateAggregator, ConfigAggregator) happening before the stubbing
3. something wrong with testkit's cwd stubs
[@W-15999401@](https://gus.lightning.force.com/a07EE00001uOfdRYAS)

test: solve nut flake

---

messages/create.md
messages/delete.md

feat: removal date in warning for org create/delete

---

package.json
src/commands/org/create/scratch.ts
src/commands/org/resume/scratch.ts
src/shared/scratchOrgOutput.ts
test/shared/scratchOrgOutput.test.ts
test/shared/scratchOrgRequest.test.ts
test/unit/org/resumeScratch.test.ts
yarn.lock

Revert multi-stage output changes to give more time for QA

fix: revert MSO changes

---

package.json
src/commands/force/org/create.ts
src/commands/org/create/sandbox.ts
src/commands/org/display.ts
src/commands/org/list.ts
src/commands/org/list/metadata-types.ts
src/commands/org/list/metadata.ts
src/commands/org/refresh/sandbox.ts
src/shared/sandboxCommandBase.ts
src/shared/sandboxProgress.ts
test/shared/sandboxProgress.test.ts
test/unit/org/display.test.ts
yarn.lock

Use new table in sf-plugins-core v12
@W-16736197@

feat: use new table

---

package.json
yarn.lock

Bump core (and jsforce)

---

src/commands/org/create/scratch.ts

Add jobId to json output when create scratch org is time out.
@W-17587775@

fix: add jobId in json output

---

.github/workflows/onRelease.yml

fix: disable ctc temporarily

---

package.json
yarn.lock

Bump sdr to 12.14.0
Bump core to 8.9.2
@W-17680614@

fix: bump sdr to pick up esr preset changes

---

messages/create_scratch.md
src/commands/org/create/scratch.ts

Doc new --snapshot flag of "org create scratch"
@W-17981185@

@W-17981185@: Doc new --snapshot flag of "org create scratch"

---

messages/messages.md
src/commands/org/open.ts
src/commands/org/open/agent.ts
src/shared/orgOpenCommandBase.ts
src/shared/orgOpenUtils.ts
test/unit/org/open.test.ts

Updates org open to use UI Bridge API to generate a single-use frontdoor URL.
[@W-17661469@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000028RCqhYAG/view)

W-17661469: use UI Bridge API to generate a single-use frontdoor

---

src/commands/org/open/agent.ts
src/shared/orgOpenCommandBase.ts
test/unit/org/open.test.ts

fixes `sf org open agent` to actually open to the builder
@W-18077630@

fix: correct retURL to startURL for OTP URLs W-18077630

---

messages/refresh.sandbox.md

W-18237102: Edit messages for new flags of "org refresh sandbox"

---

messages/resume_scratch.md
package.json
src/commands/org/resume/scratch.ts
yarn.lock

bumps sfdx-core to get: https://github.com/forcedotcom/sfdx-core/pull/1207
also adds a help msg to guide the user to set `--wait` if `org resume scratch` times out.
@W-18895089@

fix: bump dep + add msg W-18895089
